### ISSUE TITLE
Please, implement a option to save compressed table

### ISSUE THREAD

**Issue by carlosmpv** [VaiN474/salt#1]
I am developing a package that depends on data storage with tables.
When its done i will reference your package, but by now i will use a modified version that suits my needs.

Please, implement some args on save function to save without indentation.

**Comment by VaiN474** [comment]
Sure, I'll look into adding that functionality.

**Comment by VaiN474** [comment]
Implemented: fa0d48f

Updated readme with an example. ~~I haven't updated the rockspec yet, but I'll do that soon. You can just grab the script for now.~~ Let me know if this works for you.

Edit: Latest version available via LuaRocks.
